# ╔═══════════════════════════════════════════════════════════════════╗
# ║                           SunExec v1.0                            ║
# ║         Консоль в кармане - управляй сервером одной рукой!        ║
# ╚═══════════════════════════════════════════════════════════════════╝

# ᴡᴇʙsɪᴛᴇ - https://studio.sunworld.pro , ᴀᴜᴛʜᴏʀ - sᴜɴsᴛᴜᴅɪᴏ
# Нашли баг, Есть вопросы? Пишите в Discord: https://studio.sunworld.pro/discord

# Права: sunexec.use - разрешает исполнять команды в консоли. sunexec.admin - дает доступ к команде /sunexec.

# Команды:
# /sunexec - главная команда для управления плагином.
# /sunexec:exec - выполнить команду из под консоли.

# Основные настройки
settings:
  # Префикс плагина в сообщениях
  prefix: "&6[&eSunExec&6]&r"
  
  # Разрешение для использования команды
  permission: "sunexec.use"
  
  # Логировать выполненные команды в консоль
  log-commands: true

# Алиасы для команды /exec
# Алиасы регистрируются с префиксом плагина, например: /sunexec:cmd, /sunexec:execute
# Вы можете добавить любые свои алиасы
aliases:
  - "execute"
  - "console"
  - "cmd"
  - "run"

# Список игроков, которые могут использовать команду без прав
# Используйте никнеймы или UUID
whitelist:
  enabled: false
  players:
    - "PlayerName"
    - "069a79f4-44e9-4726-a5be-fca90e38aaf5"

# Сообщения плагина (Оставьте пустым, что-бы сообщение не отображалось.)
messages:
  # Сообщение при успешном выполнении команды
  command-executed: "&aКоманда &e{command} &aуспешно выполнена!"
  
  # Сообщение при ошибке выполнения
  command-error: "&cОшибка при выполнении команды: &f{error}"
  
  # Нет прав для использования команды
  no-permission: "&cУ вас нет прав для использования этой команды!"
  
  # Неверное использование команды
  usage: "&cИспользование: &e/{label} <команда>"
  
  # Сообщение при перезагрузке конфига
  config-reloaded: "&aКонфигурация успешно перезагружена!"
  
  # Команда не найдена
  command-not-found: "&cКоманда &e{command} &cне найдена!"
  
  # Только для игроков
  players-only: "&cЭту команду могут использовать только игроки!"
  
  # Только для консоли
  console-only: "&cЭту команду может использовать только консоль!"

# Настройки безопасности
security:
  # Включить блокировку команд (если false, все команды разрешены)
  enable-blocked-commands: false
  
  # Заблокированные команды (нельзя выполнить через /exec)
  blocked-commands:
    - "stop"
    - "restart"
    - "reload"
    - "op"
    - "deop"
    - "ban"
    - "ban-ip"
    - "pardon"
    
  # Режим белого списка команд (если true, можно выполнять только команды из allowed-commands)
  whitelist-mode: false
  
  # Включить белый список команд (если false, allowed-commands игнорируется)
  enable-whitelist-mode: false
  
  # Разрешенные команды (работает только если whitelist-mode: true и enable-whitelist-mode: true)
  allowed-commands:
    - "say"
    - "broadcast"
    - "give"
    - "tp"
    - "gamemode"

# Дополнительные настройки
advanced:
  # Задержка между выполнением команд (в миллисекундах)
  command-cooldown: 0
  
  # Максимальная длина команды (0 = без ограничений)
  max-command-length: 0
  
  # Показывать выполненную команду в чате исполнителю
  show-command-feedback: true